on: [push]

jobs:
  run-on-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install and cache PowerShell modules
        uses: ./
        with:
          modules-to-cache: PSFramework, Pester, dbatools:1.0.0, SpeculationControl
      - name: Show that the Action works
        shell: pwsh
        run: |
          Get-Module -Name PSFramework, Pester, dbatools, SpeculationControl -ListAvailable | Select Path -OutVariable modules
          $modules.Path.Count | Should -BeGreaterThan 1
